pipeline {
    agent any

    stages {

        stage('Clone Repo') {
            steps {
                git 'https://github.com/ashu-and-anand/devops-cicd-static-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-static-app .'
            }
        }

        stage('Tag Image') {
            steps {
                sh 'docker tag devops-static-app ashuanand/devops-static-app'
            }
        }

        stage('Push Image') {
            steps {
                sh 'docker push ashuanand/devops-static-app'
            }
        }

        stage('Deploy using Ansible') {
            steps {
                sh 'ansible-playbook -i inventory playbook.yml'
            }
        }
    }
}